#Variables
@baseUrl = http://localhost:3333

# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

#GET rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de Teste",
  "description": "Esta é uma sala de teste para verificar a criação de salas."
}

###

@roomId = {{getRooms.response.body.$.[0].id}}

###

# Get Room questions
# @name getRoomQuestions

GET {{baseUrl}}/rooms/{{roomId}}/questions